# Generated by Django 5.0.6 on 2024-08-16 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.log'),
        ),
    ]
