# Generated by Django 5.0.6 on 2024-08-16 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_journal_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='habits.log'),
        ),
    ]
